# Generated by Django 2.0.3 on 2018-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_scan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='language',
            field=models.CharField(default='eng', max_length=255),
            preserve_default=False,
        ),
    ]
