# Generated by Django 2.0.3 on 2018-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_scan_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('previous_hash', models.CharField(max_length=256)),
                ('block_hash', models.CharField(max_length=256)),
            ],
        ),
    ]
