# Generated by Django 2.0.3 on 2018-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_scan_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='doctype',
            field=models.CharField(choices=[(1, 'Birth Certificate'), (2, 'Death Certificate'), (3, 'Marriage Certificate'), (4, 'Others')], default='others', max_length=255),
            preserve_default=False,
        ),
    ]
